finish up publish workflow template

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -4,7 +4,7 @@ on:
       version:
         required: true
         type: string
-      isUnstable:
+      is-unstable:
         required: false
         default: false
         type: boolean
@@ -35,7 +35,6 @@ jobs:
           if-no-files-found: error
           path: ${{ steps.jprm.outputs.artifact }}
 
-  # TODO: finish up upload logic and align with repo server owner
   upload:
     needs:
       - build
@@ -48,7 +47,11 @@ jobs:
 
       - name: Prepare GH Release Assets
         run: |-
-          ehco '...'
+          for file in ./*; do
+            md5sum ${file#./} >> ${file%.*}.md5
+            sha256sum ${file#./} >> ${file%.*}.sha256
+          done
+          ls -l
 
       - name: Upload GH Release Assets
         uses: shogo82148/actions-upload-release-asset@v1
@@ -57,10 +60,48 @@ jobs:
           asset_path: ./*
 
       - name: Upload Jellyfin Plugin Repository Assets
+        uses: burnett01/rsync-deployments@5.2
+        with:
+          switches: -vrptz
+          path: ./*.zip
+          remote_path: /srv/repository/incoming/plugin/{{ github.repository }}/${{ inputs.version }}
+          remote_host: ${{ secrets.DEPLOY_HOST }}
+          remote_user: ${{ secrets.DEPLOY_USER }}
+          remote_key: ${{ secrets.DEPLOY_KEY }}
 
   publish:
     needs:
       - upload
     runs-on: ubuntu-latest
+    env:
+      JELLYFIN_REPO: "/srv/repository/mirror/releases/plugin/manifest-stable.json"
+      JELLYFIN_REPO_URL: "https://repo.jellyfin.org/releases/plugin/"
     steps:
       - name: Update Plugin Manifest
+        uses: appleboy/ssh-action@v0.1.4
+        with:
+          host: ${{ secrets.DEPLOY_HOST }}
+          username: ${{ secrets.DEPLOY_USER }}
+          key: ${{ secrets.DEPLOY_KEY }}
+          script_stop: true
+          envs: JELLYFIN_REPO,JELLYFIN_REPO_URL
+          script: |-
+            lock_file="/tmp/jprm.lock"
+            trap 'rm -f ${lock_file}; exit 0' SIGINT SIGTERM
+            pushd "/srv/repository/incoming/plugin/${{ github.repository }}/${{ inputs.version }}" || exit 1
+            retry=1
+            published='false'
+
+            while [[ retry -le 4 && "${published}" != "true" ]]; do
+                if [[ -e ${lock_file} ]]; then
+                    echo "Could not acquire JPRM lock! (attempt ${retry})"
+                    sleep 2
+                else
+                    touch ${lock_file}
+                    jprm --verbosity=debug repo add --url="${JELLYFIN_REPO_URL}" "${JELLYFIN_REPO}" "${ZIP_FILE}"
+                    published='true'
+                fi
+            done
+
+            popd || exit 1
+            # TODO: should this clean up the incoming folder?
